version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: rutujapawase/farmdss_backend:latest
    container_name: farmdss_backend_container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/farmdss
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    ports:
      - '8080:8080'

volumes:
  postgres_data:
    driver: local
